CREATE TABLE PRODUTO (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    preco DOUBLE NOT NULL,
    nome TEXT NOT NULL,
    descricao TEXT NOT NULL,
    tipo ENUM('HAMBURGUER', 'ACOMPANHAMENTO', 'BEBIDA') NOT NULL
);
